version: '3.8'

services:
  backend:
    volumes:
      # Mount source code for hot reloading in development
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    # For development, you might want to run npm start instead
    # This override keeps the production build but adds development settings
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - GENERATE_SOURCEMAP=false
    
  ldap:
    # Development-specific LDAP settings
    environment:
      - LDAP_LOG_LEVEL=256  # Enable debug logging
    # Uncomment to persist data during development
    # volumes:
    #   - ./ldap-dev-data:/var/lib/ldap
    #   - ./ldap-dev-config:/etc/ldap/slapd.d 