apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ldap-jwt-app
type: Opaque
data:
  # Base64 encoded values - you should change these in production
  LDAP_ADMIN_PASSWORD: YWRtaW4=  # 'admin' in base64
  LDAP_CONFIG_PASSWORD: Y29uZmln  # 'config' in base64
  LDAP_ADMIN_PASS: YWRtaW4=  # 'admin' in base64
  JWE_SECRET_KEY: dGhpc0lzQTMyQnl0ZVNlY3JldEtleTEyMzQ1Njc4OTAhIQ==  # 'thisIsA32ByteSecretKey1234567890!!' in base64 