---
# ConfigMap for ngrok configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ngrok-config
  namespace: ldap-jwt-app
data:
  ngrok.yml: |
    version: "2"
    authtoken_from_env: true
    tunnels:
      frontend:
        proto: http
        addr: frontend-service:80
        bind_tls: true
        # Enable WebSocket support
        inspect: false
        web_addr: 0.0.0.0:4040
      backend:
        proto: http
        addr: backend-service:8000
        bind_tls: true
        # Enable WebSocket support
        inspect: false

---
# Secret for ngrok auth token
apiVersion: v1
kind: Secret
metadata:
  name: ngrok-secrets
  namespace: ldap-jwt-app
type: Opaque
data:
  authtoken: ""  # Base64 encoded ngrok auth token

---
# Deployment for ngrok tunnel
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-tunnel
  namespace: ldap-jwt-app
  labels:
    app: ngrok-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok-tunnel
  template:
    metadata:
      labels:
        app: ngrok-tunnel
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:latest
        imagePullPolicy: Always
        command:
          - ngrok
          - start
          - --all
          - --config
          - /etc/ngrok/ngrok.yml
        env:
        - name: NGROK_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              name: ngrok-secrets
              key: authtoken
        ports:
        - containerPort: 4040
          name: web-ui
        volumeMounts:
        - name: config
          mountPath: /etc/ngrok
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /api/tunnels
            port: 4040
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tunnels
            port: 4040
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: ngrok-config
      restartPolicy: Always

---
# Service for ngrok web UI
apiVersion: v1
kind: Service
metadata:
  name: ngrok-web-ui
  namespace: ldap-jwt-app
  labels:
    app: ngrok-tunnel
spec:
  selector:
    app: ngrok-tunnel
  ports:
  - name: web-ui
    port: 4040
    targetPort: 4040
    nodePort: 30040
  type: NodePort 